question_data = [
        {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
         "question": "The HTML5 standard was published in 2014.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
         "question": "The common software-programming acronym &quot;I18N&quot; comes from the term &quot;Interlocalization&quot;.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
         "question": "FLAC stands for &quot;Free Lossless Audio Condenser&quot;&#039;", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                                          "question": "Linus Torvalds created Linux and Git.", "correct_answer": "True",
                                          "incorrect_answers": ["False"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
         "question": "The programming language &quot;Python&quot; is based off a modified version of &quot;JavaScript&quot;.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
         "question": "The open source program Redis is a relational database server.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                                          "question": "The Windows 7 operating system has six main editions.",
                                          "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
         "question": "The Windows ME operating system was released in the year 2000.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                                           "question": "The first dual-core CPU was the Intel Pentium D.",
                                           "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "hard",
         "question": "The T-Mobile Sidekick smartphone is a re-branded version of the Danger Hiptop.",
         "correct_answer": "True", "incorrect_answers": ["False"]}
]
